### ISSUE TITLE
pip install pointnet2_ops_lib/.

### ISSUE THREAD

**Issue by ldk-97** [ma-xu/pointMLP-pytorch#20] opened 2022-04-11 13:19 UTC
run [pip install pointnet2_ops_lib/.] error. What is this command to install? Can PointMLP run without it? Thanks!

**Comment by UnderTheMangoTree** [comment] 2022-04-11 13:25
I also can't run [pip install pointnet2_ops_lib/.] . the error is "ERROR: Command errored out with exit status 1:". Is it the same as yours?
have you solved your problem?

**Comment by ma-xu** [comment] 2022-04-11 18:57
@ldk-97 @UnderTheMangoTree Could you please post the detail error logs? It should be not so hard to install this lib.

Also, there are three ways to run without this lib.
1) use the pytorch3d lib, see https://github.com/ma-xu/pointMLP-pytorch/issues/2#issuecomment-1079764871
2) use the pytorch_geometric, see https://github.com/ma-xu/pointMLP-pytorch/issues/2#issuecomment-1079764871
3) use non-cuda operations to implement  the  furthest_point_sample, 
```
def furthest_point_sample(xyz, npoint):
    """
    Input:
        xyz: pointcloud data, [B, N, 3]
        npoint: number of samples
    Return:
        centroids: sampled pointcloud index, [B, npoint]
    """
    device = xyz.device
    B, N, C = xyz.shape
    centroids = torch.zeros(B, npoint, dtype=torch.long).to(device)
    distance = torch.ones(B, N).to(device) * 1e10
    farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
    batch_indices = torch.arange(B, dtype=torch.long).to(device)
    for i in range(npoint):
        centroids[:, i] = farthest
        centroid = xyz[batch_indices, farthest, :].view(B, 1, 3)
        dist = torch.sum((xyz - centroid) ** 2, -1)
        distance = torch.min(distance, dist)
        farthest = torch.max(distance, -1)[1]
    return centroids
```

**Comment by ldk-97** [comment] 2022-04-12 07:19
> @ldk-97 I cannot see any useful information from this. Maybe you can send me a copy of your entire error log.
> 
> Beside, there are three ways to avoid install these lib, as I mentioned above.

I sent you an email because there were so many error logs. Also I try to use the other 2 ways to solve my problem.

**Comment by ma-xu** [comment] 2022-04-12 07:27
> > @ldk-97 I cannot see any useful information from this. Maybe you can send me a copy of your entire error log.
> > Beside, there are three ways to avoid install these lib, as I mentioned above.
> 
> I sent you an email because there were so many error logs. Also I try to use the other 2 ways to solve my problem.

Received. the error probably is caused by the Windows OS. You may consider the above methods to avoid installing this lib. Let me know if you have any further questions.

**Comment by ma-xu** [comment] 2022-04-12 08:34
> > > > @ldk-97 I cannot see any useful information from this. Maybe you can send me a copy of your entire error log.
> > > > Beside, there are three ways to avoid install these lib, as I mentioned above.
> > > 
> > > 
> > > I sent you an email because there were so many error logs. Also I try to use the other 2 ways to solve my problem.
> > 
> > 
> > Received. the error probably is caused by the Windows OS. You may consider the above methods to avoid installing this lib. Let me know if you have any further questions.
> 
> Do you use the Ubuntu system? I tried to use the other ways you mentioned to solve the problem. Thanks a lot!!

Yes, Ubuntu is recommended. I will close this issue. Feel free to re-open it if necessary.

**Closed by ma-xu** 2022-04-12 08:34 UTC
