### ISSUE TITLE
About ScanObjectNN

### ISSUE THREAD

**Issue by qingfeng0830** [ma-xu/pointMLP-pytorch#13] opened 2022-03-15 11:33 UTC
When i python main.py in classification_ScanObjectNN，show
 File "D:\software\Anaconda\envs\pct\lib\site-packages\h5py\_hl\files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 100, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'F:\Project\pointMLP-pytorch-main\classification_ScanObjectNN/data/h5_files/main_split/training_objectdataset_augmentedrot_scale75.
h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Please how should i solve this problem

**Comment by ma-xu** [comment] 2022-03-15 14:07
@qingfeng0830 
I have to say the path is wrong:
F:\Project\pointMLP-pytorch-main\classification_ScanObjectNN/data/h5_files/main_split/training_objectdataset_augmentedrot_scale75.h5

See "\" and "/" in the above path, caused by the difference path names in Windows and Lunix. 

One solution is that you may manually replace all "/" to "\" to fit Windows OS, this may help solve this problem.

I would **STRONGLY** suggest to test our codes on Lunix, we will not support Windows.

**Comment by qingfeng0830** [comment] 2022-03-16 00:44
Thank you for your answer, I will try it under ubuntu

**Comment by ma-xu** [comment] 2022-03-23 17:57
@qingfeng0830 I will close this issue since there is no further discussion. Feel free to reopen it if necessary.

**Closed by ma-xu** 2022-03-23 17:57 UTC

**Comment by jc991206** [comment] 2024-05-18 13:42
> 谢谢你

> 谢谢你的回答，我会在ubuntu下尝试

How to generate visualization files of scanobjectnn and shapenet and visualize them Thank you very much
